### ISSUE TITLE
Users can Log In to the App

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#102]
_As a test provider I want to be able to log in to the app so that I can securely and safely log test results and report them to my public health department._

**Describe the solution you'd like and the specific acceptance criteria to be completed**
Users are able to log into the app, and receive a personalized and authenticated experience.

**Acceptance Criteria**
- [x] Authentication service is selected #89 
- [ ] A user account can be created using the authentication service for the pilot
- [ ] UI for the login experience is ready to go (Could be a part of #99 ) 
- [ ] A user can log into the app, and the app knows who they are and what organization they belong to (Future: need to flesh out the access controls or classes users would have) #135
- [ ] Make sure only logged in users can access the app
- [ ]  UI to say 'you've been logged out' and a timer of some sort to auto log out #144
- [ ] Something in-app to show who is logged in the app #135
- [ ] Offer a log out method #135  

**Additional context**
This ticket does not include different roles or role based access. Everyone is an admin right now.
Password resets are not included. (unless it's easy and makes sense to add it)

**Comment by willusds** [comment]
Breaking out into smaller tickets #144 , #99, #135, closing this
