### ISSUE TITLE
Epic: Saving Data to the Cloud

### ISSUE THREAD

**Issue by aliciabeckett-gov** [CDCgov/prime-central#105]
_As someone who administers COVID tests, I want to know that if my computer explodes or my browser cache is wiped I will not lose my data, so that my test results are saved for future use and audits._

_As someone who administers COVID tests, I want to share a patient/people list and facility settings with other users at my organization, so that we don't each have to add them they are available all the time no matter who is running the test or the browser they are using._

**Describe the solution you'd like and the specific acceptance criteria to be completed**

- [ ] There is a database that can hold test results, people, and facility settings from the app in a cloud environment
- [ ] The app syncs/saves test results to the cloud
- [ ] The app loads previous test results from the cloud that were performed by that organization including from other users
- [ ] The app makes the test results available to the data hub
- [ ] The app saves newly added or updated people to the cloud see #100 and #101 
- [ ] The app loads previously added people from the cloud and makes them available in the test queue and manage people pages

This is build a backend that can store data, and sync data between the app and the backend. It's a big epic, and if we need to we can break it up but it's more to track the different pieces and how far along we are on them.

Leads on this (breaking this into smaller chunks):
@timothybest-usds @benwarfield-usds @nickrobison-usds

**Comment by aliciabeckett-gov** [comment]
@willusds @sharmaneil I forgot this one today during grooming. It's a giant epic to build the backend. It would be awesome if we could start it this sprint.

**Comment by aliciabeckett-gov** [comment]
POCketReport

Or POCit, like pocket but POC-it and it can work on the phone in your pocket!

**Comment by aliciabeckett-gov** [comment]
On a serious note, let's call it by EOW.

**Comment by sharmaneil** [comment]
We didn't have our eng sync today, I'd like 30min during tomorrow's (thursday's) collab time. I'd love to get a digest from @RickHawesUSDS about how deploying hasura + postgres to Azure went, as well as @benwarfield-usds's thoughts if/when he has a chance to take a gander.

If we decide to run with that particular tech stack, the immediate next steps would be to:
- get it running on the rest of the dev's machines for local development
- create sandbox & stage environments in Azure with it that is wired into our CI/CD pipelines

I only suggested Hasura since it appeared to have more out-of-the-box support for auth and postgres and thus could save us time. If for whatever reason we want to move away from Hasura but keep graphql, Pete suggested a viable alternative: https://github.com/graphql/express-graphql

I don't foresee any problems with GraphQL as the API standard, unless the team feels strongly that a traditional REST approach would be meaningfully faster to implement.

**Comment by willusds** [comment]
Break out sub task tickets for Sprint 4

**Comment by aliciabeckett-gov** [comment]
Closing in favor of other tickets
