### ISSUE TITLE
Improve Workflow (have to beat CSV)

### ISSUE THREAD

**Issue by willusds** [CDCgov/prime-central#124]
**Features / Needs:**
- [ ] Add 15 min timer
- [ ] Add ability to see PCR test results
- [ ] Show who is due for a test
- [ ] Track who is in their infectious period
- [ ] Track who does not need to be retested (tested positive and finished quarantine)
- [ ] Other things we find along the way with usability testing and rollout

**Comment by willusds** [comment]
Broken out into other tickets
