### ISSUE TITLE
Design unauthenticated homepage

### ISSUE THREAD

**Issue by katiealoisi** [CDCgov/prime-central#99]
Design a homepage for the unauthenticated user experience. This page should allow users to learn more about the app and log into the app.

- [x] Design web page
- [x] Design Log In Experience
- [x] Make branding and logo #94

**Comment by katiealoisi** [comment]
Design mock ups for application homepage, incorporating:
* About section
* Contact us
* Login

What other content would we need?
* FAQs?

**Comment by katiealoisi** [comment]
@cygov Does any of this content (e.g. for About or FAQs) already exist?

**Comment by pete-gov** [comment]
Hey team, want to make sure you eyeball #79 and consider this in the design, specifically:

Design is lacking on what the desired UI/UX should be if there are no patients:
* should it redirect to the Patients page if there are no patients? I think the desired landing page in general is the TestQueue
* if there are no TestResults, should the test result table be empty, or should there be a more human-friendly message? ie: "There are no test results"
* same with if there are no Patients.

**Comment by katiealoisi** [comment]
I think these are a little different.

As I understand it, the homepage in this issue is a public facing page (pre-login) that anyone can visit to learn about the app and sign up. @aliciabeckett-gov Is this what you were referring to a few days ago? We talked about contracting with a vendor to build this out.

I think #79 is referring to the landing page, post-login. 
* In my opinion, the desired landing page should be the TestQueue.
* If there are no TestResults, "No test results".
* If there are no Patients, "No patients".

Would love thoughts from @hmyers-cms too.

**Comment by aliciabeckett-gov** [comment]
Got it, thanks for clarifying!

**Comment by aliciabeckett-gov** [comment]
@hmyers-cms @cygov @katiealoisi - is this something we can or should do this sprint (the design not the development)?

**Comment by cygov** [comment]
> @cygov Does any of this content (e.g. for About or FAQs) already exist?

There are FAQs [here](https://docs.google.com/document/d/1DTi8JkG27WJtpw-nGZ2CUAWgaY50bNSPM6eYJ72SRPA/edit). It's a really long list developed from an early document Rick helped compile.

Would be helpful to chat about our audiences and pick the ones that would be most relevant to them, or group the Q in a more intuitive way.

**Comment by katiealoisi** [comment]
@hmyers-cms and I just chatted about this - we can likely start the homepage design during this sprint but will probably not finish this sprint. We'd like to prioritize the user testing + getting the app designs finalized. Also going to split this ticket - we'll keep this one for the design and create another for the content creation. On that ticket, I'll tag you @cygov and we can have that convo about the audiences and content!

**Comment by aliciabeckett-gov** [comment]
Okay, moved this ticket into this sprint.

**Comment by willusds** [comment]
Related to #82

**Comment by aliciabeckett-gov** [comment]
Login will happen through Okta. This site will link to the Okta login.

**Comment by willusds** [comment]
Completed with simplereport.cdc.gov!
